export const INITIALIZE = "INITIALIZE";
export const UPDATE = "UPDATE"
export const UPDATE_PLAYER_BET = "UPDATE_PLAYER_BET";
export const UPDATE_PLAYER_HAND = "UPDATE_PLAYER_HAND";
export const UPDATE_DEALER_HAND = "UPDATE_DEALER_HAND";

export const PLAYER_BET = "PLAYER_BET";
export const PLAYER_HIT = "PLAYER_HIT";
export const PLAYER_STAY = "PLAYER_STAY";

export const PLAYER_JOINED = 'PLAYER_JOINED';
export const PLAYER_LEFT = 'PLAYER_LEFT';
